upstream cart_upstream {
    server host.docker.internal:3001;  # Windows host port mapping
    server host.docker.internal:3001 backup;
}
server {
    listen 8080;
    location / {
        proxy_pass http://cart_upstream;
    }
}
